#!/bin/bash
MODE=${1:-default}

function install_cask {
    # cf. https://github.com/cask/cask
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
}

function copy_config {
    echo "Create symbolic link files"
    cd $(dirname $0)

    for filename in .?*; do
        case $filename in
            '..' | '.git' | '.DS_Store')
                continue;;
            *.example)
                echo "${PWD}/${filename} -> ${HOME}/${filename%.*}"
                cp -i "${PWD}/${filename}" "${HOME}/${filename%.*}"
                continue;;
            *)
                echo "${PWD}/${filename} -> ${HOME}/${filename}"
                rm -rf "${HOME}/${filename}"
                ln -Fis "${PWD}/${filename}" $HOME
                ;;
        esac
    done
}

function setup_default {
    copy_config
    echo ""

    source "${HOME}/.bashrc"

    echo "Run cask"
    cd "${HOME}/.emacs.d"
    cask
}

case $MODE in
    cask)
        install_cask
        ;;
    config)
        copy_config
        ;;
    default)
        setup_default
        ;;
    *)
        echo "'${MODE}' is not support mode"
        ;;
esac
