#!/bin/zsh

set -Ceu

usage() {
	echo "Usage: $0 [MODE]" 1>&2
	exit 1
}

copy_config() {
	echo "Create symbolic link files"
	cd $(dirname "$0")

	for filename in .?*; do
		case $filename in
		'..' | '.git' | '.DS_Store')
			continue
			;;
		*.example)
			echo "${PWD}/${filename} -> ${HOME}/${filename%.*}"
			cp -i "${PWD}/${filename}" "${HOME}/${filename%.*}"
			continue
			;;
		*)
			echo "${PWD}/${filename} -> ${HOME}/${filename}"
			rm -rf "${HOME}/${filename}"
			ln -Fis "${PWD}/${filename}" "$HOME"
			;;
		esac
	done
}

install_deps() {
	if ! type brew >/dev/null 2>&1; then
		echo "brew not found" 1>&2
		exit 1
	fi

	echo "Install dependencies"
	cd $(dirname "$0")
	brew bundle
}

install_runtimes() {
	if ! type asdf >/dev/null 2>&1; then
		echo "asdf not found" 1>&2
		exit 1
	fi

	echo "Install programing runtimes"
	asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
	asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
	asdf plugin-add python
}

main() {
	while getopts h opt; do
		case $opt in
		h)
			usage
			;;
		esac
	done

	shift $((OPTIND - 1))

	local mode=${1:-default}

	case $mode in
	config)
		copy_config
		;;
	deps)
		install_deps
		;;
	runtimes)
		install_runtimes
		;;
	default)
		copy_config
		source "${HOME}/.zshrc"
		install_runtimes
		source "${HOME}/.zshrc"
		;;
	*)
		echo "'${mode}' is not a supported mode" 1>&2
		usage
		;;
	esac
}

main "$@"
