#!/bin/bash

DOTFILES_DIR=$(dirname $0)

# create symbolic link files
cd $DOTFILES_DIR

for filename in .?*; do
    case $filename in
        '..' | '.git' | '.DS_Store')
            continue;;
        *.example)
            continue;;
        *)
            echo "${PWD}/${filename} -> ${HOME}/${filename}"
            rm -rf "${HOME}/${filename}"
            ln -Fis "${PWD}/${filename}" $HOME
            ;;
    esac
done

# update emacs lisps
cd "${DOTFILES_DIR}/.emacs.d"

echo "download elisp"
cask
