(source gnu)
(source melpa)

(depends-on "use-package")
(depends-on "auto-complete")
(depends-on "undo-tree")
(depends-on "smartparens")
(depends-on "anzu")

(depends-on "markdown-mode+")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "go-mode")
