(source gnu)
(source melpa)
(source org)

(depends-on "use-package")

(depends-on "auto-complete")
(depends-on "undo-tree" :git "https://github.com/martijnvermaat/undo-tree.git")
(depends-on "smartparens")
(depends-on "smart-newline")
(depends-on "anzu")
(depends-on "rainbow-mode" :git "https://github.com/emacsmirror/rainbow-mode.git")

(depends-on "rjsx-mode")
(depends-on "typescript-mode")
(depends-on "coffee-mode")
(depends-on "go-mode")
(depends-on "ruby-mode")
(depends-on "ruby-end")
(depends-on "php-mode")
(depends-on "processing-mode")

(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "haml-mode")
(depends-on "jade-mode")

(depends-on "scss-mode")
(depends-on "stylus-mode")

(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "markdown-mode+")
